# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a356385177d8492baaea9a8050394a51850f707342e3c7a86a98f980d75f2d690c74d5389bf47cdcfb1230550eb5cbd5d1c9d86274930f082ab306e3b1833eb

test:
  secret_key_base: 245688ad5b50f78432b855c466a2386617e2535cbf9f2500638b097d305ca5d5f6ba172c521c3b46ee3a8c425205bb3a66f4caa14aabdb5b2fac2ccdec233f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
